/* AUTO-GENERATED by build_deck_data.py - curated `file` entries are
   preserved via brand_logos.json (CURATED_LOGOS) at build time. */
window.FLORENCE_LOGOS = {
  "hca": {
    "domain": "hcahealthcare.com",
    "file": "assets/systems/hca.svg"
  },
  "va": {
    "domain": "va.gov",
    "file": null
  },
  "commonspirit": {
    "domain": "commonspirit.org",
    "file": "assets/systems/commonspirit.svg"
  },
  "lifepoint_health": {
    "domain": "lifepointhealth.net",
    "file": null
  },
  "ascension": {
    "domain": "ascension.org",
    "file": "assets/systems/ascension.svg"
  },
  "scionhealth": {
    "domain": "scionhealth.com",
    "file": null
  },
  "trinity_health": {
    "domain": "trinity-health.org",
    "file": "assets/systems/trinity_health.svg"
  },
  "advocate_health": {
    "domain": "advocatehealth.org",
    "file": "assets/systems/advocate_health.svg"
  },
  "christus_health": {
    "domain": "christushealth.org",
    "file": null
  },
  "community_health_systems": {
    "domain": "chs.net",
    "file": "assets/systems/community_health_systems.svg"
  },
  "adventhealth": {
    "domain": "adventhealth.com",
    "file": "assets/systems/adventhealth.svg"
  },
  "sanford_health": {
    "domain": "sanfordhealth.org",
    "file": null
  },
  "mercy_health": {
    "domain": "mercy.net",
    "file": null
  },
  "prime_healthcare": {
    "domain": "primehealthcare.com",
    "file": null
  },
  "baylor_scott_white": {
    "domain": "bswhealth.com",
    "file": "assets/systems/baylor_scott_white.svg"
  },
  "providence": {
    "domain": "providence.org",
    "file": "assets/systems/providence.svg"
  },
  "tenet_healthcare": {
    "domain": "tenethealth.com",
    "file": "assets/systems/tenet_healthcare.svg"
  },
  "bon_secours_mercy_health": {
    "domain": "bsmhealth.com",
    "file": null
  },
  "ochsner": {
    "domain": "ochsner.org",
    "file": null
  },
  "upmc": {
    "domain": "upmc.com",
    "file": "assets/systems/upmc.svg"
  },
  "kaiser_permanente": {
    "domain": "kp.org",
    "file": "assets/partners/kp-logo.png"
  },
  "avera_health": {
    "domain": "avera.org",
    "file": null
  },
  "intermountain_health": {
    "domain": "intermountainhealthcare.org",
    "file": null
  },
  "banner_health": {
    "domain": "bannerhealth.com",
    "file": null
  },
  "jefferson_health": {
    "domain": "jeffersonhealth.org",
    "file": null
  },
  "ardent_health": {
    "domain": "ardenthealth.com",
    "file": null
  },
  "northwell_health": {
    "domain": "northwell.edu",
    "file": "assets/systems/northwell_health.svg"
  },
  "texas_health_resources": {
    "domain": "texashealth.org",
    "file": null
  },
  "universal_health_services": {
    "domain": "uhsinc.com",
    "file": null
  },
  "adventist_health": {
    "domain": "adventisthealth.org",
    "file": null
  },
  "piedmont_healthcare": {
    "domain": "piedmont.org",
    "file": null
  },
  "orlando_health": {
    "domain": "orlandohealth.com",
    "file": null
  },
  "west_virginia_university_health_system": {
    "domain": "wvumedicine.org",
    "file": null
  },
  "baptist_memorial_health_care_corporation": {
    "domain": "baptistonline.org",
    "file": null
  },
  "community_hospital_corporation": {
    "domain": "communityhospitalcorp.com",
    "file": null
  },
  "ssm_health": {
    "domain": "ssmhealth.com",
    "file": null
  },
  "cleveland_clinic": {
    "domain": "clevelandclinic.org",
    "file": "assets/systems/cleveland_clinic.svg"
  },
  "sutter_health": {
    "domain": "sutterhealth.org",
    "file": null
  },
  "university_of_california_health": {
    "domain": "universityofcalifornia.edu",
    "file": "assets/systems/university_of_california_health.svg"
  },
  "altru_health_system": {
    "domain": "altru.org",
    "file": null
  },
  "northbay_healthcare": {
    "domain": "northbay.org",
    "file": null
  },
  "honorhealth": {
    "domain": "honorhealth.com",
    "file": null
  },
  "mass_general_brigham": {
    "domain": null,
    "file": "assets/systems/mass_general_brigham.svg"
  },
  "new_york_presbyterian_healthcare_system": {
    "domain": null,
    "file": "assets/systems/new_york_presbyterian_healthcare_system.svg"
  },
  "new_york_city_health_and_hospitals_corporation": {
    "domain": null,
    "file": "assets/systems/new_york_city_health_and_hospitals_corporation.svg"
  },
  "corewell_health": {
    "domain": null,
    "file": "assets/systems/corewell_health.svg"
  },
  "mayo_clinic": {
    "domain": null,
    "file": "assets/systems/mayo_clinic.svg"
  }
};

window.FLORENCE_ACCENTS = {"hca": "#092240", "trinity_health": "#9CC860", "ascension": "#1B4297", "northwell_health": "#0059A5", "advocate_health": "#7E82C2", "adventhealth": "#005C95", "providence": "#00338E", "commonspirit": "#BA4896", "cleveland_clinic": "#0468CD", "university_of_california_health": "#1295D8", "kaiser_permanente": "#006BA6", "mass_general_brigham": "#008BB0", "tenet_healthcare": "#1F6094", "upmc": "#6E267B", "new_york_presbyterian_healthcare_system": "#E2231A", "community_health_systems": "#006C68", "new_york_city_health_and_hospitals_corporation": "#1E478E", "corewell_health": "#67F48C", "mayo_clinic": "#0E3293", "baylor_scott_white": "#003DA5"};

window.florenceFavicon = function (id) {
  var m = window.FLORENCE_LOGOS[id];
  if (!m || !m.domain) return null;
  return 'https://www.google.com/s2/favicons?domain=' + m.domain + '&sz=64';
};
window.florenceLogoFile = function (id) {
  var m = window.FLORENCE_LOGOS[id];
  return (m && m.file) || null;
};
