/* AUTO-GENERATED by build_deck_data.py - curated `file` entries are
   preserved via CURATED_LOGOS at the top of the build script. */
window.FLORENCE_LOGOS = {
  "hca": {
    "domain": "hcahealthcare.com",
    "file": null
  },
  "va": {
    "domain": "va.gov",
    "file": null
  },
  "commonspirit": {
    "domain": "commonspirit.org",
    "file": null
  },
  "lifepoint_health": {
    "domain": "lifepointhealth.net",
    "file": null
  },
  "ascension": {
    "domain": "ascension.org",
    "file": null
  },
  "scionhealth": {
    "domain": "scionhealth.com",
    "file": null
  },
  "trinity_health": {
    "domain": "trinity-health.org",
    "file": null
  },
  "advocate_health": {
    "domain": "advocatehealth.org",
    "file": null
  },
  "christus_health": {
    "domain": "christushealth.org",
    "file": null
  },
  "community_health_systems": {
    "domain": "chs.net",
    "file": null
  },
  "adventhealth": {
    "domain": "adventhealth.com",
    "file": null
  },
  "sanford_health": {
    "domain": "sanfordhealth.org",
    "file": null
  },
  "mercy_health": {
    "domain": "mercy.net",
    "file": null
  },
  "prime_healthcare": {
    "domain": "primehealthcare.com",
    "file": null
  },
  "baylor_scott_white": {
    "domain": "bswhealth.com",
    "file": null
  },
  "providence": {
    "domain": "providence.org",
    "file": null
  },
  "tenet_healthcare": {
    "domain": "tenethealth.com",
    "file": null
  },
  "bon_secours_mercy_health": {
    "domain": "bsmhealth.com",
    "file": null
  },
  "ochsner": {
    "domain": "ochsner.org",
    "file": null
  },
  "upmc": {
    "domain": "upmc.com",
    "file": null
  },
  "kaiser_permanente": {
    "domain": "kp.org",
    "file": "assets/partners/kp-logo.png"
  },
  "avera_health": {
    "domain": "avera.org",
    "file": null
  },
  "intermountain_health": {
    "domain": "intermountainhealthcare.org",
    "file": null
  },
  "banner_health": {
    "domain": "bannerhealth.com",
    "file": null
  },
  "jefferson_health": {
    "domain": "jeffersonhealth.org",
    "file": null
  },
  "ardent_health": {
    "domain": "ardenthealth.com",
    "file": null
  },
  "northwell_health": {
    "domain": "northwell.edu",
    "file": null
  },
  "texas_health_resources": {
    "domain": "texashealth.org",
    "file": null
  },
  "universal_health_services": {
    "domain": "uhsinc.com",
    "file": null
  },
  "adventist_health": {
    "domain": "adventisthealth.org",
    "file": null
  },
  "piedmont_healthcare": {
    "domain": "piedmont.org",
    "file": null
  },
  "orlando_health": {
    "domain": "orlandohealth.com",
    "file": null
  },
  "west_virginia_university_health_system": {
    "domain": "wvumedicine.org",
    "file": null
  },
  "baptist_memorial_health_care_corporation": {
    "domain": "baptistonline.org",
    "file": null
  },
  "community_hospital_corporation": {
    "domain": "communityhospitalcorp.com",
    "file": null
  },
  "ssm_health": {
    "domain": "ssmhealth.com",
    "file": null
  },
  "cleveland_clinic": {
    "domain": "clevelandclinic.org",
    "file": null
  },
  "sutter_health": {
    "domain": "sutterhealth.org",
    "file": null
  },
  "university_of_california_health": {
    "domain": "universityofcalifornia.edu",
    "file": null
  },
  "altru_health_system": {
    "domain": "altru.org",
    "file": null
  },
  "northbay_healthcare": {
    "domain": "northbay.org",
    "file": null
  },
  "honorhealth": {
    "domain": "honorhealth.com",
    "file": null
  }
};

window.florenceFavicon = function (id) {
  var m = window.FLORENCE_LOGOS[id];
  if (!m || !m.domain) return null;
  return 'https://www.google.com/s2/favicons?domain=' + m.domain + '&sz=64';
};
window.florenceLogoFile = function (id) {
  var m = window.FLORENCE_LOGOS[id];
  return (m && m.file) || null;
};
